# Punkt 9: Umlaute in VBA-Dateien wiederherstellen
# Speichert als Windows-1252 (cp1252)

$ErrorActionPreference = "Stop"

# Umlaut-Konstanten als Code-Points (Windows-1252)
$ae = [char]228; $oe = [char]246; $ue = [char]252
$AE = [char]196; $OE = [char]214; $UE = [char]220
$ss = [char]223

# Wörterbuch als geordnetes Array von Paaren [pattern, replacement]
# WICHTIG: Längere Patterns ZUERST (case-sensitive)
$rules = @(
    # ß-Wörter (zwei Konsonanten umflanken Sound)
    @("au${ss}ergew" + $oe + "hnlich", "außergewöhnlich"),  # already has umlaut hint
    @("au?ergew?hnlich", "au${ss}ergew${oe}hnlich"),
    @("au?erhalb",    "au${ss}erhalb"),
    @("au?erdem",     "au${ss}erdem"),
    @("Au?erdem",     "Au${ss}erdem"),
    @("au?er",        "au${ss}er"),
    @("Au?er",        "Au${ss}er"),
    @("gr??enordn",   "gr${oe}${ss}enordn"),
    @("gr??ten",      "gr${oe}${ss}ten"),
    @("gr??te",       "gr${oe}${ss}te"),
    @("Gr??te",       "Gr${oe}${ss}te"),
    @("gr??er",       "gr${oe}${ss}er"),
    @("Gr??er",       "Gr${oe}${ss}er"),
    @("Gr??e",        "Gr${oe}${ss}e"),
    @("gr??e",        "gr${oe}${ss}e"),
    @("schlie?lich",  "schlie${ss}lich"),
    @("Schlie?lich",  "Schlie${ss}lich"),
    @("schlie?en",    "schlie${ss}en"),
    @("Schlie?en",    "Schlie${ss}en"),
    @("schlie?t",     "schlie${ss}t"),
    @("hei?t",        "hei${ss}t"),
    @("hei?en",       "hei${ss}en"),
    @("Stra?e",       "Stra${ss}e"),
    @("stra?e",       "stra${ss}e"),
    @("wei?",         "wei${ss}"),
    @("Wei?",         "Wei${ss}"),
    @("gewi?",        "gewi${ss}"),
    @("gro?",         "gro${ss}"),
    @("Gro?",         "Gro${ss}"),
    @("lie?",         "lie${ss}"),
    @("Lie?",         "Lie${ss}"),
    @("flie?en",      "flie${ss}en"),
    @("Flie?en",      "Flie${ss}en"),
    @("genie?",       "genie${ss}"),
    @("Genie?",       "Genie${ss}"),
    @("gie?",         "gie${ss}"),
    @("Gie?",         "Gie${ss}"),
    @("verlie?",      "verlie${ss}"),
    @("beschlie?",    "beschlie${ss}"),
    @("Beschlie?",    "Beschlie${ss}"),
    @("erschlie?",    "erschlie${ss}"),
    @("aufschlie?",   "aufschlie${ss}"),
    @("Gru?",         "Gru${ss}"),
    @("gru?",         "gru${ss}"),
    @("regelm??ig",   "regelm${ae}${ss}ig"),
    @("Regelm??ig",   "Regelm${ae}${ss}ig"),
    @("rechtm??ig",   "rechtm${ae}${ss}ig"),
    @("gleichm??ig",  "gleichm${ae}${ss}ig"),
    @("m??ig",        "m${ae}${ss}ig"),
    @("M??ig",        "M${ae}${ss}ig"),
    @("gem??",        "gem${ae}${ss}"),
    @("unverh?ltnism??ig", "unverh${ae}ltnism${ae}${ss}ig"),
    @("Anst??e",      "Anst${oe}${ss}e"),

    # Ü
    @("?bersicht",    "${UE}bersicht"),
    @("?bertrag",     "${UE}bertrag"),
    @("?berschrift",  "${UE}berschrift"),
    @("?berschreib",  "${UE}berschreib"),
    @("?berschritt",  "${UE}berschritt"),
    @("?berpr?f",     "${UE}berpr${ue}f"),
    @("?bernehm",     "${UE}bernehm"),
    @("?bernimm",     "${UE}bernimm"),
    @("?bernomm",     "${UE}bernomm"),
    @("?bergeb",      "${UE}bergeb"),
    @("?berge",       "${UE}berge"),
    @("?bung",        "${UE}bung"),
    @("?brig",        "${ue}brig"),
    @("?ber",         "${UE}ber"),
    @("zur?ck",       "zur${ue}ck"),
    @("Zur?ck",       "Zur${ue}ck"),
    @("ZUR?CK",       "ZUR${UE}CK"),
    @("Gl?ck",        "Gl${ue}ck"),
    @("gl?ck",        "gl${ue}ck"),
    @("St?ck",        "St${ue}ck"),
    @("st?ck",        "st${ue}ck"),
    @("Br?ck",        "Br${ue}ck"),
    @("br?ck",        "br${ue}ck"),
    @("Br?cke",       "Br${ue}cke"),
    @("Dr?ck",        "Dr${ue}ck"),
    @("dr?ck",        "dr${ue}ck"),
    @("R?ck",         "R${ue}ck"),
    @("r?ck",         "r${ue}ck"),
    @("g?ltig",       "g${ue}ltig"),
    @("G?ltig",       "G${ue}ltig"),
    @("ung?ltig",     "ung${ue}ltig"),
    @("Ung?ltig",     "Ung${ue}ltig"),
    @("GR?N",         "GR${UE}N"),
    @("gr?n",         "gr${ue}n"),
    @("Gr?n",         "Gr${ue}n"),
    @("Pr?fung",      "Pr${ue}fung"),
    @("pr?fung",      "pr${ue}fung"),
    @("Pr?f",         "Pr${ue}f"),
    @("pr?f",         "pr${ue}f"),
    @("PR?F",         "PR${UE}F"),
    @("gepr?f",       "gepr${ue}f"),
    @("ausf?hr",      "ausf${ue}hr"),
    @("Ausf?hr",      "Ausf${ue}hr"),
    @("durchf?hr",    "durchf${ue}hr"),
    @("Durchf?hr",    "Durchf${ue}hr"),
    @("einf?hr",      "einf${ue}hr"),
    @("Einf?hr",      "Einf${ue}hr"),
    @("ausgef?hr",    "ausgef${ue}hr"),
    @("eingef?hr",    "eingef${ue}hr"),
    @("durchgef?hr",  "durchgef${ue}hr"),
    @("aufgef?hr",    "aufgef${ue}hr"),
    @("unterst?tz",   "unterst${ue}tz"),
    @("Unterst?tz",   "Unterst${ue}tz"),
    @("st?tz",        "st${ue}tz"),
    @("St?tz",        "St${ue}tz"),
    @("k?nstl",       "k${ue}nstl"),
    @("K?nstl",       "K${ue}nstl"),
    @("k?rz",         "k${ue}rz"),
    @("K?rz",         "K${ue}rz"),
    @("F?r ",         "F${ue}r "),
    @("f?r ",         "f${ue}r "),
    @("f?r:",         "f${ue}r:"),
    @("f?r,",         "f${ue}r,"),
    @("f?r.",         "f${ue}r."),
    @("F?rs ",        "F${ue}rs "),
    @("f?rs ",        "f${ue}rs "),
    @("rechtsb?ndig", "rechtsb${ue}ndig"),
    @("linksb?ndig",  "linksb${ue}ndig"),
    @("b?ndig",       "b${ue}ndig"),
    @("B?ndig",       "B${ue}ndig"),
    @("m?ssen",       "m${ue}ssen"),
    @("M?ssen",       "M${ue}ssen"),
    @("m?sste",       "m${ue}sste"),
    @("M?sste",       "M${ue}sste"),
    @("m?ssten",      "m${ue}ssten"),
    @("fl?ssig",      "fl${ue}ssig"),
    @("Fl?ssig",      "Fl${ue}ssig"),
    @("Gr?nde",       "Gr${ue}nde"),
    @("gr?nde",       "gr${ue}nde"),
    @("Gr?nd",        "Gr${ue}nd"),
    @("gr?nd",        "gr${ue}nd"),
    @("verg?t",       "verg${ue}t"),
    @("Verg?t",       "Verg${ue}t"),
    @("beg?nstig",    "beg${ue}nstig"),
    @("verg?nstig",   "verg${ue}nstig"),
    @("Verg?nstig",   "Verg${ue}nstig"),
    @("verf?gbar",    "verf${ue}gbar"),
    @("Verf?gbar",    "Verf${ue}gbar"),
    @("verf?g",       "verf${ue}g"),
    @("Verf?g",       "Verf${ue}g"),
    @("gen?g",        "gen${ue}g"),
    @("Gen?g",        "Gen${ue}g"),
    @("unverz?glich", "unverz${ue}glich"),
    @("urspr?nglich", "urspr${ue}nglich"),
    @("Urspr?nglich", "Urspr${ue}nglich"),
    @("urspr?ng",     "urspr${ue}ng"),
    @("gegen?ber",    "gegen${ue}ber"),
    @("Gegen?ber",    "Gegen${ue}ber"),
    @("einf?g",       "einf${ue}g"),
    @("Einf?g",       "Einf${ue}g"),
    @("eingef?g",     "eingef${ue}g"),
    @("hinzuf?g",     "hinzuf${ue}g"),
    @("Hinzuf?g",     "Hinzuf${ue}g"),
    @("hinzugef?g",   "hinzugef${ue}g"),
    @("verkn?pf",     "verkn${ue}pf"),
    @("Verkn?pf",     "Verkn${ue}pf"),
    @("Geb?hr",       "Geb${ue}hr"),
    @("geb?hr",       "geb${ue}hr"),
    @("Schl?ssel",    "Schl${ue}ssel"),
    @("schl?ssel",    "schl${ue}ssel"),
    @("Datentr?ger",  "Datentr${ae}ger"),
    @("Tr?ger",       "Tr${ae}ger"),
    @("tr?ger",       "tr${ae}ger"),
    @("M?lleimer",    "M${ue}lleimer"),
    @("M?ll",         "M${ue}ll"),
    @("m?ll",         "m${ue}ll"),
    @("M?ssen",       "M${ue}ssen"),
    @("d?rfen",       "d${ue}rfen"),
    @("D?rfen",       "D${ue}rfen"),
    @("d?rf",         "d${ue}rf"),
    @("D?rf",         "D${ue}rf"),
    @("erw?nscht",    "erw${ue}nscht"),
    @("unerw?nscht",  "unerw${ue}nscht"),
    @("w?nschen",     "w${ue}nschen"),
    @("W?nschen",     "W${ue}nschen"),
    @("gew?nscht",    "gew${ue}nscht"),
    @("Gew?nscht",    "Gew${ue}nscht"),
    @("ben?tzt",      "ben${ue}tzt"),
    @("ber?cksichtig","ber${ue}cksichtig"),
    @("Ber?cksichtig","Ber${ue}cksichtig"),
    @("k?nnte",       "k${oe}nnte"),
    @("K?nnte",       "K${oe}nnte"),
    @("k?nnten",      "k${oe}nnten"),
    @("K?nnten",      "K${oe}nnten"),
    @("k?nnen",       "k${oe}nnen"),
    @("K?nnen",       "K${oe}nnen"),
    @("k?nnt",        "k${oe}nnt"),
    @("K?nnt",        "K${oe}nnt"),
    @("k?nn",         "k${oe}nn"),
    @("K?nn",         "K${oe}nn"),

    # Ö
    @("?ffnen",       "${OE}ffnen"),
    @("?ffne",        "${oe}ffne"),
    @("ge?ffnet",     "ge${oe}ffnet"),
    @("?konom",       "${OE}konom"),
    @("?sterr",       "${OE}sterr"),
    @("l?schen",      "l${oe}schen"),
    @("L?schen",      "L${oe}schen"),
    @("l?sch",        "l${oe}sch"),
    @("L?sch",        "L${oe}sch"),
    @("L?SCH",        "L${OE}SCH"),
    @("gel?sch",      "gel${oe}sch"),
    @("L?sung",       "L${oe}sung"),
    @("l?sung",       "l${oe}sung"),
    @("aufl?s",       "aufl${oe}s"),
    @("Aufl?s",       "Aufl${oe}s"),
    @("st?r",         "st${oe}r"),
    @("St?r",         "St${oe}r"),
    @("gest?rt",      "gest${oe}rt"),
    @("h?her",        "h${oe}her"),
    @("H?her",        "H${oe}her"),
    @("h?chst",       "h${oe}chst"),
    @("H?chst",       "H${oe}chst"),
    @("erh?h",        "erh${oe}h"),
    @("Erh?h",        "Erh${oe}h"),
    @("h?h",          "h${oe}h"),
    @("H?h",          "H${oe}h"),
    @("sch?n",        "sch${oe}n"),
    @("Sch?n",        "Sch${oe}n"),
    @("pers?nlich",   "pers${oe}nlich"),
    @("Pers?nlich",   "Pers${oe}nlich"),
    @("pl?tzlich",    "pl${oe}tzlich"),
    @("Pl?tzlich",    "Pl${oe}tzlich"),
    @("m?glich",      "m${oe}glich"),
    @("M?glich",      "M${oe}glich"),
    @("Unm?glich",    "Unm${oe}glich"),
    @("unm?glich",    "unm${oe}glich"),
    @("erm?glich",    "erm${oe}glich"),
    @("Erm?glich",    "Erm${oe}glich"),
    @("m?cht",        "m${oe}cht"),
    @("M?cht",        "M${oe}cht"),
    @("h?ren",        "h${oe}ren"),
    @("H?ren",        "H${oe}ren"),
    @("geh?r",        "geh${oe}r"),
    @("Geh?r",        "Geh${oe}r"),
    @("angeh?r",      "angeh${oe}r"),
    @("verm?gen",     "verm${oe}gen"),
    @("Verm?gen",     "Verm${oe}gen"),
    @("verm?g",       "verm${oe}g"),
    @("Verm?g",       "Verm${oe}g"),
    @("k?rper",       "k${oe}rper"),
    @("K?rper",       "K${oe}rper"),
    @("h?fl",         "h${oe}fl"),
    @("H?fl",         "H${oe}fl"),
    @("verz?ger",     "verz${oe}ger"),
    @("Verz?ger",     "Verz${oe}ger"),
    @("verz?gerung",  "verz${oe}gerung"),
    @("Verz?gerung",  "Verz${oe}gerung"),
    @("M?ge",         "M${oe}ge"),
    @("m?ge",         "m${oe}ge"),
    @("M?gen",        "M${oe}gen"),
    @("m?gen",        "m${oe}gen"),
    @("gel?st",       "gel${oe}st"),
    @("Gel?st",       "Gel${oe}st"),
    @("aufgel?st",    "aufgel${oe}st"),
    @("ungel?st",     "ungel${oe}st"),

    # Ä
    @("?nderung",     "${AE}nderung"),
    @("?ndern",       "${AE}ndern"),
    @("?ndere",       "${AE}ndere"),
    @("?ndert",       "${AE}ndert"),
    @("ge?ndert",     "ge${ae}ndert"),
    @("?nderbar",     "${AE}nderbar"),
    @("?hnlichkeit",  "${AE}hnlichkeit"),
    @("?hnlich",      "${AE}hnlich"),
    @("?hnel",        "${AE}hnel"),
    @("?u?erst",      "${AE}u${ss}erst"),
    @("?u?ern",       "${AE}u${ss}ern"),
    @("?u?er",        "${AE}u${ss}er"),
    @("?lteste",      "${ae}lteste"),
    @("?ltere",       "${ae}ltere"),
    @("?lter",        "${ae}lter"),
    @("?lt",          "${ae}lt"),
    @("erkl?r",       "erkl${ae}r"),
    @("Erkl?r",       "Erkl${ae}r"),
    @("gekl?r",       "gekl${ae}r"),
    @("aufkl?r",      "aufkl${ae}r"),
    @("ungef?hr",     "ungef${ae}hr"),
    @("gef?hr",       "gef${ae}hr"),
    @("Gef?hr",       "Gef${ae}hr"),
    @("g?ng",         "g${ae}ng"),
    @("G?ng",         "G${ae}ng"),
    @("verl?nge",     "verl${ae}nge"),
    @("Verl?nge",     "Verl${ae}nge"),
    @("l?nger",       "l${ae}nger"),
    @("L?nger",       "L${ae}nger"),
    @("l?nge",        "l${ae}nge"),
    @("L?nge",        "L${ae}nge"),
    @("l?ng",         "l${ae}ng"),
    @("L?ng",         "L${ae}ng"),
    @("st?ndig",      "st${ae}ndig"),
    @("St?ndig",      "St${ae}ndig"),
    @("verst?nd",     "verst${ae}nd"),
    @("Verst?nd",     "Verst${ae}nd"),
    @("unbest?ndig",  "unbest${ae}ndig"),
    @("best?tig",     "best${ae}tig"),
    @("Best?tig",     "Best${ae}tig"),
    @("best?nd",      "best${ae}nd"),
    @("Best?nd",      "Best${ae}nd"),
    @("tats?chlich",  "tats${ae}chlich"),
    @("Tats?chlich",  "Tats${ae}chlich"),
    @("verf?ng",      "verf${ae}ng"),
    @("umf?ng",       "umf${ae}ng"),
    @("Umf?ng",       "Umf${ae}ng"),
    @("getr?g",       "getr${ae}g"),
    @("eintr?g",      "eintr${ae}g"),
    @("Eintr?g",      "Eintr${ae}g"),
    @("Eintr?ge",     "Eintr${ae}ge"),
    @("Eintr?gen",    "Eintr${ae}gen"),
    @("Vortr?ge",     "Vortr${ae}ge"),
    @("Auftr?g",      "Auftr${ae}g"),
    @("auftr?g",      "auftr${ae}g"),
    @("antr?g",       "antr${ae}g"),
    @("Antr?g",       "Antr${ae}g"),
    @("betr?g",       "betr${ae}g"),
    @("Betr?g",       "Betr${ae}g"),
    @("tr?gt",        "tr${ae}gt"),
    @("Tr?gt",        "Tr${ae}gt"),
    @("tr?g",         "tr${ae}g"),
    @("Tr?g",         "Tr${ae}g"),
    @("k?m",          "k${ae}m"),
    @("K?m",          "K${ae}m"),
    @("sp?ter",       "sp${ae}ter"),
    @("Sp?ter",       "Sp${ae}ter"),
    @("sp?t",         "sp${ae}t"),
    @("Sp?t",         "Sp${ae}t"),
    @("l?dt",         "l${ae}dt"),
    @("L?dt",         "L${ae}dt"),
    @("erh?ltlich",   "erh${ae}ltlich"),
    @("Erh?ltlich",   "Erh${ae}ltlich"),
    @("erh?lt",       "erh${ae}lt"),
    @("Erh?lt",       "Erh${ae}lt"),
    @("enth?lt",      "enth${ae}lt"),
    @("Enth?lt",      "Enth${ae}lt"),
    @("beh?lt",       "beh${ae}lt"),
    @("Beh?lt",       "Beh${ae}lt"),
    @("verh?lt",      "verh${ae}lt"),
    @("Verh?lt",      "Verh${ae}lt"),
    @("h?ufig",       "h${ae}ufig"),
    @("H?ufig",       "H${ae}ufig"),
    @("zul?ssig",     "zul${ae}ssig"),
    @("unzul?ssig",   "unzul${ae}ssig"),
    @("Zul?ssig",     "Zul${ae}ssig"),
    @("zus?tzlich",   "zus${ae}tzlich"),
    @("Zus?tzlich",   "Zus${ae}tzlich"),
    @("s?mtlich",     "s${ae}mtlich"),
    @("S?mtlich",     "S${ae}mtlich"),
    @("aufr?um",      "aufr${ae}um"),
    @("R?um",         "R${ae}um"),
    @("r?um",         "r${ae}um"),
    @("erw?hn",       "erw${ae}hn"),
    @("Erw?hn",       "Erw${ae}hn"),
    @("Datens?tze",   "Datens${ae}tze"),
    @("Datens?tzen",  "Datens${ae}tzen"),
    @("S?umnis",      "S${ae}umnis"),
    @("s?umnis",      "s${ae}umnis"),
    @("S?umni",       "S${ae}umni"),
    @("s?umni",       "s${ae}umni"),
    @("erg?nz",       "erg${ae}nz"),
    @("Erg?nz",       "Erg${ae}nz"),
    @("k?rzlich",     "k${ue}rzlich"),
    @("K?rzlich",     "K${ue}rzlich"),
    @("h?ngen",       "h${ae}ngen"),
    @("H?ngen",       "H${ae}ngen"),
    @("aufh?ng",      "aufh${ae}ng"),
    @("zug?nglich",   "zug${ae}nglich"),
    @("unzug?nglich", "unzug${ae}nglich"),
    @("h?lt",         "h${ae}lt"),
    @("H?lt",         "H${ae}lt"),
    @("l?sst",        "l${ae}sst"),
    @("L?sst",        "L${ae}sst"),
    @("z?hlerwechsel","z${ae}hlerwechsel"),
    @("Z?hlerwechsel","Z${ae}hlerwechsel"),
    @("Z?hler",       "Z${ae}hler"),
    @("z?hler",       "z${ae}hler"),
    @("Z?HLER",       "Z${AE}HLER"),
    @("aufz?hl",      "aufz${ae}hl"),
    @("Aufz?hl",      "Aufz${ae}hl"),
    @("erz?hl",       "erz${ae}hl"),
    @("Erz?hl",       "Erz${ae}hl"),
    @("gez?hlt",      "gez${ae}hlt"),
    @("gez?hl",       "gez${ae}hl"),
    @("z?hlt",        "z${ae}hlt"),
    @("Z?hlt",        "Z${ae}hlt"),
    @("Z?hl",         "Z${ae}hl"),
    @("z?hl",         "z${ae}hl"),
    @("Z?HL",         "Z${AE}HL"),
    @("S?ulen",       "S${ae}ulen"),
    @("H?lfte",       "H${ae}lfte"),
    @("h?lfte",       "h${ae}lfte"),
    @("H?nde",        "H${ae}nde"),
    @("h?nde",        "h${ae}nde"),
    @("h?nd",         "h${ae}nd"),
    @("H?nd",         "H${ae}nd"),
    @("Pl?tze",       "Pl${ae}tze"),
    @("Bel?ge",       "Bel${ae}ge"),
    @("W?hrung",      "W${ae}hrung"),
    @("w?hrend",      "w${ae}hrend"),
    @("W?hrend",      "W${ae}hrend"),
    @("W?hr",         "W${ae}hr"),
    @("w?hr",         "w${ae}hr"),
    @("erw?hl",       "erw${ae}hl"),
    @("Erw?hl",       "Erw${ae}hl"),
    @("gew?hlt",      "gew${ae}hlt"),
    @("gew?hl",       "gew${ae}hl"),
    @("W?hl",         "W${ae}hl"),
    @("w?hl",         "w${ae}hl"),
    @("j?hrlich",     "j${ae}hrlich"),
    @("J?hrlich",     "J${ae}hrlich"),
    @("j?hrl",        "j${ae}hrl"),
    @("J?hrl",        "J${ae}hrl"),
    @("Ger?t",        "Ger${ae}t"),
    @("ger?t",        "ger${ae}t"),
    @("ben?tig",      "ben${oe}tig"),
    @("Ben?tig",      "Ben${oe}tig"),
    @("gen?tig",      "gen${oe}tig"),
    @("gel?ufig",     "gel${ae}ufig"),
    @("l?uf",         "l${ae}uf"),
    @("L?uf",         "L${ae}uf"),
    @("r?uml",        "r${ae}uml"),
    @("R?uml",        "R${ae}uml"),
    @("erkl?rung",    "erkl${ae}rung"),
    @("Erkl?rung",    "Erkl${ae}rung"),
    @("Sch?tz",       "Sch${ue}tz"),
    @("sch?tz",       "sch${ue}tz"),
    @("gesch?tz",     "gesch${ue}tz"),
    @("Gesch?tz",     "Gesch${ue}tz"),
    @("ungesch?tz",   "ungesch${ue}tz"),

    # Wahrscheinl. Restwörter
    @("Mitgliedstr?ger", "Mitgliedstr${ae}ger"),
    @("hinz?fug",     "hinz${ue}fug"),
    @("Eintr?gt",     "Eintr${ae}gt"),
    @("eintr?gt",     "eintr${ae}gt")
)

# Backup
$ts = Get-Date -Format "yyyyMMdd_HHmmss"
$backupRoot = "vba\BackUp_Punkt9_$ts"
New-Item -ItemType Directory -Path $backupRoot -Force | Out-Null

$files = @()
$files += Get-ChildItem -Path "vba\Modules" -Filter "*.bas" -File
$files += Get-ChildItem -Path "vba\Classes" -Filter "*.cls" -File

$cp1252 = [System.Text.Encoding]::GetEncoding(1252)

$totalReps = 0
$filesChanged = 0

foreach ($f in $files) {
    Copy-Item $f.FullName -Destination (Join-Path $backupRoot $f.Name) -Force
    
    $content = [System.IO.File]::ReadAllText($f.FullName, $cp1252)
    $original = $content
    $fileReps = 0
    
    foreach ($rule in $rules) {
        $pat = $rule[0]; $rep = $rule[1]
        if ($content.Contains($pat)) {
            # Count occurrences
            $idx = 0; $cnt = 0
            while (($idx = $content.IndexOf($pat, $idx)) -ge 0) {
                $cnt++; $idx += $pat.Length
            }
            $content = $content.Replace($pat, $rep)
            $fileReps += $cnt
        }
    }
    
    if ($content -ne $original) {
        [System.IO.File]::WriteAllText($f.FullName, $content, $cp1252)
        $filesChanged++
        $totalReps += $fileReps
        Write-Host "  $($f.Name): $fileReps Ersetzungen"
    }
}

Write-Host ""
Write-Host "FERTIG: $filesChanged Dateien, $totalReps Ersetzungen total." -ForegroundColor Green
Write-Host "Backup: $backupRoot" -ForegroundColor Yellow

Write-Host ""
Write-Host "Top 15 Dateien mit verbleibenden '?'-Zeichen:" -ForegroundColor Yellow
$files | ForEach-Object {
    $txt = [System.IO.File]::ReadAllText($_.FullName, $cp1252)
    $cnt = ([regex]::Matches($txt, '\?')).Count
    [PSCustomObject]@{ File = $_.Name; QuestionMarks = $cnt }
} | Sort-Object QuestionMarks -Descending | Select-Object -First 15 | Format-Table -AutoSize
